#!/usr/bin/env python3
"""Refresh INDEX.md from tracked-skills.json using live GitHub star counts.

Stdlib only. Reads GITHUB_TOKEN from the environment when present (raises the
API rate limit from 60/hr to 5000/hr); works unauthenticated for local runs.
"""

import json
import os
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "tracked-skills.json"
SNAPSHOT = ROOT / ".skill-index-snapshot.json"
OUTPUT = ROOT / "INDEX.md"

START = "<!-- SKILL-INDEX:START -->"
END = "<!-- SKILL-INDEX:END -->"


def fetch(repo):
    """Return repo metadata, or None if the slug no longer resolves."""
    request = urllib.request.Request(
        f"https://api.github.com/repos/{repo}",
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "skill-index-updater",
        },
    )
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        request.add_header("Authorization", f"Bearer {token}")

    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return json.load(response)
    except urllib.error.HTTPError as error:
        if error.code == 404:
            print(f"  ! {repo} did not resolve (renamed, deleted or private)")
            return None
        raise


def human(count):
    if count >= 1000:
        return f"{count / 1000:.1f}k".replace(".0k", "k")
    return str(count)


def delta(current, previous):
    if previous is None or current is None:
        return ""
    change = current - previous
    if change == 0:
        return ""
    return f"{'+' if change > 0 else ''}{human(change) if abs(change) >= 1000 else change}"


def main():
    config = json.loads(CONFIG.read_text())
    previous = json.loads(SNAPSHOT.read_text()) if SNAPSHOT.exists() else {}

    rows = {}
    snapshot = {}
    for entry in config["skills"]:
        repo = entry["repo"]
        print(f"  fetching {repo}")
        data = fetch(repo)
        stars = data["stargazers_count"] if data else None
        if stars is not None:
            snapshot[repo] = stars
        rows.setdefault(entry["tier"], []).append(
            {
                "repo": repo,
                "note": entry["note"],
                "stars": stars,
                "delta": delta(stars, previous.get(repo)),
                "url": data["html_url"] if data else f"https://github.com/{repo}",
                "archived": bool(data and data.get("archived")),
                "missing": data is None,
            }
        )

    if not snapshot:
        print("No repository resolved -- refusing to overwrite INDEX.md", file=sys.stderr)
        return 1

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines = [START, f"_Star counts refreshed {stamp}._", ""]

    for tier in config["tiers"]:
        entries = rows.get(tier["id"])
        if not entries:
            continue
        entries.sort(key=lambda row: row["stars"] or -1, reverse=True)
        lines += [
            f"## {tier['label']}",
            "",
            f"_{tier['blurb']}_",
            "",
            "| Stars | Change | Repo | Why I track it |",
            "| ----: | :----- | :--- | :------------- |",
        ]
        for row in entries:
            flags = ""
            if row["missing"]:
                flags = " **(unresolved)**"
            elif row["archived"]:
                flags = " **(archived)**"
            stars = human(row["stars"]) if row["stars"] is not None else "--"
            lines.append(
                f"| {stars} | {row['delta']} | [{row['repo']}]({row['url']}){flags} | {row['note']} |"
            )
        lines.append("")

    lines += [
        "<sub>Generated by `scripts/update_index.py`. Edit `tracked-skills.json`, not this table.</sub>",
        END,
    ]
    block = "\n".join(lines)

    existing = OUTPUT.read_text() if OUTPUT.exists() else ""
    if START in existing and END in existing:
        head, _, rest = existing.partition(START)
        _, _, tail = rest.partition(END)
        rendered = head + block + tail
    else:
        header = f"# {config['title']}\n\n{config['subtitle']}\n\n"
        rendered = header + block + "\n"

    OUTPUT.write_text(rendered)
    SNAPSHOT.write_text(json.dumps(snapshot, indent=2, sort_keys=True) + "\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(snapshot)} repos resolved)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
